### ISSUE TITLE
Should check fgets() return value

### ISSUE THREAD

**Issue by tdb** [i-scream/libstatgrab#71] opened 2015-08-20 21:03 UTC
```
process_stats.c: In function 'sg_get_process_stats_int':
process_stats.c:480:9: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
    fgets(read_buf, READBUF_LENGTH, f);
         ^
```

Introduced in ca9fa7749d7773910e9870cafcf4862f0ff1b39a (on master - not yet released).

**Comment by rehsack** [comment] 2018-11-14 18:18
duplicate of #91 (seriously #91 is a duplicate of #71, but #91 is fixed ^^)

**Closed by rehsack** 2018-11-14 18:18 UTC
